### ISSUE TITLE
1.1.0 won't build on OS X Yosemite 10.10

### ISSUE THREAD

**Issue by jeregrine** [saponinsky/erl-scrypt#4]
```
==> scrypt
==> scrypt (compile)
Compiling c_src/scrypt.c
In file included from c_src/scrypt.c:33:
~/projects/erlangs/17.0/erts-6.0/include/erl_nif.h:27:12: fatal error: 'config.h' file not found
#  include "config.h"
           ^
1 error generated.
ERROR: compile failed while processing ~/projects/abutment/deps/scrypt: rebar_abort
```
